name:                dovin
version:             3.0.1
github:              "xaviershay/dovin"
license:             BSD3
author:              "Xavier Shay"
maintainer:          "contact@xaviershay.com"
copyright:           "2021 Xavier Shay"

extra-source-files:
- README.md

synopsis: "A proof assistant for Magic: The Gathering puzzles."
category: "Games"

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/xaviershay/dovin#dovin>

custom-setup:
  dependencies:
    - base >= 4.7 && < 5
    - Cabal
    - directory
    - filepath

dependencies:
  - base >= 4.7 && < 5
  - containers
  - hashable
  - lens
  - mtl
  - unordered-containers
  - parsec
  - split

library:
  source-dirs: src

executables:
  dovin:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dovin

tests:
  dovin-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wunused-imports
    dependencies:
    - dovin
    - tasty
    - tasty-discover
    - tasty-hunit
    - tasty-quickcheck
